version: "3"
services:
  httpd:
    image: httpd:2.4.41-alpine
    volumes:
      - $PWD:/usr/local/apache2/htdocs
    # Follows are security holes !!!!!
    ports:
      - 8080:80
  proxy:
    image: fareoffice/modsecurity:3-nginx
    environment:
      PARANOIA: 3
      # SEC_RULE_ENGINE: On
      PROXY_UPSTREAM_HOST: httpd:80
    ports:
      - 80:80
